# https://taskfile.dev

version: '2'

vars:
  STACK: CdkInspecStack

tasks:

  build:
    sources:
      - lib/*.ts
      - bin/*.ts
    generates:
      - lib/*.js
      - bin/*.js
    cmds:
      - npm run build


# CDK tasks


  update:
    desc: install latest cdk and other modules
    cmds:
      - ncu -u
      - npm install

  deploy:
    desc: deploy stack without asking
    deps: [build]
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      - cdk deploy {{.STACK}} --require-approval never --profile $AWSUME_PROFILE

  destroy:
    desc: destroy stack without asking
    cmds:
      - cmd: echo Profile $AWSUME_PROFILE
        silent: true
      - cdk destroy "*" --force --profile $AWSUME_PROFILE


  diff:
    desc: cdk diff inl. tsc
    deps: [build]
    cmds:
      - cdk diff {{.STACK}}


  edge-of-tomorrow:
    desc: deploy destroy repeat
    cmds:
      - task: update
      - task: deploy
      - task: destroy
  
